import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    "projects-overview",
    {
      type: "category",
      label: "Path Header Scanner",
      link: {
        type: "doc",
        id: "path-header-scanner/index",
      },
      items: [{ type: "autogenerated", dirName: "path-header-scanner" }],
    },
    {
      type: "category",
      label: "Doc Gen",
      link: {
        type: "doc",
        id: "doc-gen/index",
      },
      items: [{ type: "autogenerated", dirName: "doc-gen" }],
    },
    {
      type: "category",
      label: "Reflow",
      link: {
        type: "doc",
        id: "reflow/index",
      },
      items: [{ type: "autogenerated", dirName: "reflow" }],
    },
    {
      type: "category",
      label: "Custy",
      link: {
        type: "doc",
        id: "custy/index",
      },
      items: [{ type: "autogenerated", dirName: "custy" }],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
