flowchart TD

A[Install Reflow]

B[Initialize Project]

C[Configure Project]

D[Git Tags]

E[Convert Tags]

F[Replay Releases]

G[Dockerize Images]

H[Container Registry]

A --> B

B --> C

C --> D

D --> E

E --> F

F --> G

G --> H
