server {
    listen 8080;
    listen [::]:8080;

    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    charset utf-8;
    server_tokens off;

    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "healthy\n";
    }

    location = / {
        return 302 /devalltect-docs/;
    }

    location /devalltect-docs/ {
        try_files $uri $uri/ $uri.html =404;
    }

    error_page 404 /devalltect-docs/404.html;

    location = /devalltect-docs/404.html {
        internal;
    }
}
